config/routes.rb
Cmunity::Application.routes.draw do

  # Devise Routes

  devise_for :users do
    get "login" => "devise/sessions#new", :as => :login
    delete "logout" => "devise/sessions#destroy", :as => :logout
    get "register" => "devise/registrations#new", :as => :register
  end
  # Root

  root :to => 'home#index'
  
  match "mycommunities" => "groups#index_my_groups"
  match "communities" => "groups#index"
  match "fetch" => "url_posts#fetch"
  match "fetchvid" => "video_posts#fetch"
  match "fetchimg" => "image_posts#fetch"

  #Autogenerated routes
  match "group_message" => "groups#send_message"
  
  #Autogenerated routes
  resources :activities
  resources :groups
  resources :users

  resources :contents, :path => "posts", :constraints => {:id => /[0-9]+/}, :as => "posts"
  resources :event_posts, :path => "posts/events", :as => "events"
  resources :video_posts, :path => "posts/videos", :as => "videos"
  resources :text_posts, :path => "posts/texts", :as => "texts"
  resources :url_posts, :path => "posts/urls", :as => "urls"
  resources :image_posts, :path => "posts/images", :as => "images"

  resources :memberships

end

app/views/display/_event.haml
.span5
  .page-header.no-bottom-padding{:style => "margin-bottom: 10px;"}
    %h3.no-bottom-margin 
      = content.title
      %small 
        #{content.is_private ? "Private" : "Public"} #{content.type} &middot; #{content.creator.name} 
  %p 
    %span.text-info= content.mediable.start_date.strftime('%B %-d, %Y')
    at #{content.mediable.start_time.strftime('%l:%M %P')} 
    %span.muted until 
    %span.text-info= content.mediable.end_date.strftime('%B %-d, %Y')
    at #{content.mediable.end_time.strftime('%l:%M %P')}
  
  %blockquote
    %p= content.description


.span3.well{:style => "text-align:center;"}
  = image_tag content.mediable.photo.url(:medium), :class => 'img-rounded'
  %br
  %strong Posted #{time_ago_in_words(content.created_at)} ago
  %br
  %strong Location:
  = content.mediable.location
  %br
  %strong.text-success= content.mediable.is_all_day ? "This is an all day event" : ""
  - if current_user == content.creator
    = link_to "Destory", event_path, :class => "btn btn-danger"
    = link_to "Edit", edit_event_path(content.mediable), :class => "btn"

app/views/display/_image.haml
.page-header
  %h3 
    = content.title
    %small{:style => "display:block;"} 
      #{content.is_private ? "Private" : "Public"} #{content.type} &middot; #{content.creator.name} 
.row-fluid.text-center
  %img.img-polaroid{:src => content.mediable.image_url}
.row-fluid
  %i.icon-share
  %small 
    permalink:    
    #{link_to content.mediable.image_url, content.mediable.image_url }
  %blockquote
    = content.description
- if current_user == content.creator
  = link_to "Destory", image_path, :class => "btn btn-danger"
  = link_to "Edit", edit_image_path(content.mediable), :class => "btn"

app/views/display/_text.haml
.page-header
  %h3 
    = content.title
    %small{:style => "display:block;"} 
      #{content.is_private ? "Private" : "Public"} #{content.type} &middot; #{content.creator.name} 
%blockquote
  = content.mediable.text
  %small content.creator.name
- if current_user == content.creator
  = link_to "Destory", text_path, :class => "btn btn-danger"
  = link_to "Edit", edit_text_path(content.mediable), :class => "btn"

app/views/display/_url.haml
.page-header
  %h3 
    = content.title
    %small{:style => "display:block;"} 
      #{content.is_private ? "Private" : "Public"} #{content.type.upcase} &middot; #{content.creator.name} 

.row-fluid.text-center
  %img.img-polaroid{:src => content.mediable.image_url, :style => "margin: 10px 0;" }
.row-fluid
  %i.icon-share
  %small 
    permalink:    
    #{link_to content.mediable.url, content.mediable.url }
  %blockquote{:style => "margin: 10px 0;"}
    %p= content.description
  - if current_user == content.creator
    = link_to "Destory", url_path, :class => "btn btn-danger"
    = link_to "Edit", edit_url_path(content.mediable), :class => "btn"

app/views/display/_video.haml
.page-header
  %h3 
    = content.title
    %small{:style => "display:block;"} 
      #{content.is_private ? "Private" : "Public"} #{content.type} &middot;
      - if !content.post_as.nil?
        = content.creator_group.name
      - else
        = content.creator.name

.row-fluid.text-center
  = content.mediable.embed_code.html_safe
.row-fluid
  %i.icon-share
  %small 
    permalink:    
    #{link_to content.mediable.video_url, content.mediable.video_url }
  %blockquote{:style => "margin: 10px 0;"}
    %p= content.description
  - if current_user == content.creator
    = link_to "Destory", video_path, :class => "btn btn-danger"
    = link_to "Edit", edit_video_path(content.mediable), :class => "btn"