config/routes.rb
Cmunity::Application.routes.draw do

  # Devise Routes

  devise_for :users do
    get "login" => "devise/sessions#new", :as => :login
    delete "logout" => "devise/sessions#destroy", :as => :logout
    get "register" => "devise/registrations#new", :as => :register
  end
  # Root

  root :to => 'home#index'
  
  match "mycommunities" => "groups#index_my_groups"
  match "communities" => "groups#index"
  match "fetch" => "url_posts#fetch"
  match "fetchvid" => "video_posts#fetch"
  match "fetchimg" => "image_posts#fetch"

  #Autogenerated routes
  match "group_message" => "groups#send_message"
  
  #Autogenerated routes
  resources :activities
  resources :groups
  resources :users

  resources :contents, :path => "posts", :constraints => {:id => /[0-9]+/}, :as => "posts"
  resources :event_posts, :path => "posts/events", :as => "events"
  resources :video_posts, :path => "posts/videos", :as => "videos"
  resources :text_posts, :path => "posts/texts", :as => "texts"
  resources :url_posts, :path => "posts/urls", :as => "urls"
  resources :image_posts, :path => "posts/images", :as => "images"

  resources :memberships

end

app/models/group.rb
class Group < ActiveRecord::Base

  resourcify
  has_many :contents, :foreign_key => 'parent_group_id'
  has_many :contents, :foreign_key => 'post_as'
  has_many :memberships, :dependent => :destroy
  has_many :users, :through => :memberships
  has_many :roles, :as => :resource
  has_many :activities, :as => :owner
  has_many :approvals
  has_many :approvals, :as => :sender
  has_many :cosponsors, :foreign_key => 'sender_id'
  has_many :cosponsors, :foreign_key => 'receiver_id'
  has_one :creator
  
  # has_many :event_posts, :through => :cosponsors, :foreign_key => 'event_id'
  # has_many :event_posts, :through => :contents, :source => :mediable, :source_type => "EventPost"
  # has_many :image_posts, :through => :contents, :source => :mediable, :source_type => "ImagePost"
  # has_many :text_posts, :through => :contents, :source => :mediable, :source_type => "TextPost"
  # has_many :url_posts, :through => :contents, :source => :mediable, :source_type => "UrlPost"
  # has_many :video_posts, :through => :contents, :source => :mediable, :source_type => "VideoPost"

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>"}
  attr_accessible :name, :description, :users_to_message, :message
  attr_reader :users_to_message, :message
  
  # Validations
  validates :name, :presence => true, :length => { :minimum => 2 }, :uniqueness => true
  validates :description, :presence => true, :length => { :minimum => 5 }
  #validates_attachment :avatar, :presence => true, :content_type => { :content_type => "image/jpg" }, :size => { :in => 0..1000.kilobytes }
  #validates_with AttachmentPresenceValidator, :attributes => :avatar
  
  def isMessageValid?(message)
    if !(message.length > 1 )
      self.errors.add(message, "can not be empty")
    end
    
    return ( message.length > 1 )
  end
  
  def isMemberValid?(members)
    if members.nil?
      return false
    end
    
    return (members.size > 0)
  end
  
  def find_admin
      gid = self.id
      User.joins{roles}.where{(roles.name.eq 'admin') & (roles.resource_type.eq 'Group') & (roles.resource_id.eq gid)}.first
  end

  def can_manage?(user)
    if user.nil?
      false
    elsif user.has_role? 'admin', self
      true
    elsif user.has_role? 'member', self
      false
    else
      false
    end
  end

  def get_contents
    self.contents
  end

  def get_officers
    self.roles
  end

  def get_member_names
    self.users.collect(&:name)
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource
  helper ApplicationHelper
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.order('updated_at DESC').paginate(:page => params[:page], :per_page => 10)
    @CU = current_user
    
    #logged in
    @myGroups = current_user.groups.order('updated_at DESC').paginate(:page => params[:page], :per_page => 10) unless current_user.nil?
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end
  
  # GET /mygroups
  # GET /mygroups.json
  def index_my_groups
    #logged in
    @myGroups = current_user.groups.paginate(:page => params[:page], :per_page => 10) unless current_user.nil?
    
    respond_to do |format|
      format.html # index_my_groups.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end
  
  def send_message
    @group = Group.find(params[:group][:id])
    
    members = params[:group]["users_to_message"]
    members.reject! { |m| m.empty? }
    message = params[:group]["message"]
    
    logger.debug "Members: #{members}"
    
    if (@group.isMessageValid?(message) && @group.isMemberValid?(members))
      members.each do |u|
        user = User.find(u)
        self.twilio(user.cell, message) unless user.cell.nil?
      end
      
      
      
      redirect_to groups_url, notice: 'Message Sent.'
      return
      
    else
      
      if !(@group.isMemberValid?(message))
        redirect_to group_path(@group), alert: "Please select members to send message"
        return
      end
      
      if !(@group.isMessageValid?(message))
        redirect_to group_path(@group), alert: "Message must be at least 1 character"
        return
      end
      
    end
  end

  def twilio(number_to_send_to, the_message)
    twilio_sid = "ACb18218cb24a64fe207de2f020d414ed7"
    twilio_token = "08faea04bc6260e3204e32c7898e5f4a"
    twilio_phone_number = "4128880020"
 
    @twilio_client = Twilio::REST::Client.new twilio_sid, twilio_token
 
    @twilio_client.account.sms.messages.create(
      :from => "+1#{twilio_phone_number}",
      :to => number_to_send_to,
      :body => the_message
    )
  end
  
  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])
    @group.memberships.build(:user => current_user, :group => @group)
    
    respond_to do |format|
      if @group.save
        track_activity @group
        current_user.add_role :admin, @group
        format.html { redirect_to groups_url, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        track_activity @group
        format.html { redirect_to groups_url, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    name = @group.name #needed for output message
    @group.destroy
    track_activity @group
    respond_to do |format|
      format.html { redirect_to groups_url, notice: "#{name} group was deleted." }
      format.json { head :no_content }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_all_groups.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= Group.human_attribute_name(:name) %></th>
      <th>Admin</th>
      <th># of Members</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.name, group_path(group) %></td>
        <td><%= link_to group.find_admin.name, user_path(group.find_admin) unless group.find_admin.nil? %></td>
        <td><%= group.users.count %></td>
        <% if group.can_manage?(current_user) %>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_group_path(group), :class => 'btn btn-mini' %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @groups, :renderer => BootstrapPagination::Rails %>

app/views/groups/_form.html.erb
<%= form_for @group, :html => { :class => 'form-horizontal' } do |f| %>
  <% @group.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>
  <div class="control-group">
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field', :placeholder => "Community Name" %>
    </div>
  </div>
	
  <div class="control-group">
    <div class="controls">
      <%= f.text_area :description, :class => 'text_field', :placeholder => "Description", :size => "20x3" %>
    </div>
  </div>
	
  <div class="form-actions">
    <%= f.submit "Create", :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), groups_path, :class => 'btn' %>
		
		<% if params[:action] == 'edit' %>
			<%= link_to("Delete", group_path, :method => :delete,
									:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), 
		              :class => 'btn btn-danger' ) %>
		<% end %>
		
  </div>
<% end %>

app/views/groups/_group_message_user_select.html.erb
<%= form_for @group, :url => group_message_path, :html => { :class => 'form-horizontal' } do |f| %>
  <% @group.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>
  <div class="control-group">
    <div class="controls">
      <%= f.select :users_to_message, options_for_select(@group.users.collect {|u| [ u.name, u.id ] }), {}, {:multiple => true} %>
    </div>
  </div>
	
  <div class="control-group">
    <div class="controls">
      <%= f.text_area :message, :class => 'text_field', :placeholder => "Hi, just a reminder for our meeting on Wednesday...", :size => "20x3" %>
    </div>
  </div>
	
	<div><%= f.hidden_field :id, value: @group.id %></div>
	
  <div class="form-actions">
    <%= f.submit "Send Messages", :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/groups/_my_groups.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= Group.human_attribute_name(:name) %></th>
      <th># of Members</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @myGroups.each do |group| %>
      <tr>
        <td><%= link_to group.name, group_path(group) %></td>
				<td><%= group.users.count %></td>
        <% if group.can_manage?(current_user) %>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_group_path(group), :class => 'btn btn-mini' %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @myGroups, :renderer => BootstrapPagination::Rails %>

app/views/groups/edit.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/groups/index.html.erb
<!-- <% if not @myGroups.nil? %>
	<div class="page-header">
	  <h1>My Communities</h1>
	</div>
	<%= render :partial => 'my_groups' %>
	<br />
<% end %> -->

<% if not @groups.nil? %>
	<div class="page-header">
	  <h1>All Communities</h1>
	</div>
	<%= render :partial => 'all_groups' %>
<% end %>
<% if user_signed_in? %>
	<%= link_to t('.new', :default => t("helpers.links.new")), new_group_path, :class => 'btn btn-primary' %>
	<br />
<% end %>

app/views/groups/index_my_groups.html.erb
<div class="page-header">
  <h1>My Communities</h1>
</div>

<% if not @myGroups.nil? %>
	<%= render :partial => 'my_groups' %>
<% end %>
<% if user_signed_in? %>
	<%= link_to t('.new', :default => t("helpers.links.new")),
	            new_group_path,
	            :class => 'btn btn-primary' %>
<% end %>

app/views/groups/new.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1>Create Community</h1>
</div>

<%= render :partial => 'form' %>

app/views/groups/send_message.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1>Wrong place</h1>
</div>

app/views/groups/show.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%= @group.name %></h1>
</div>

<h4>Description</h4>
<p><%= @group.description %></p>


<% if current_user && current_user.is_member?(@group) %>
	<p>You are a member of this group. Should change this to officer/add special features here.</p>
<% end %>


<h4>Members</h4>
<ul>
  <% @group.get_member_names.each do |name| %>
    <li><%= name %></li>
  <% end %>
</ul>

<% if current_user && current_user.is_member?(@group) %>
<hr/>
	<h4>Message Members</h4>
	<%= render :partial => 'group_message_user_select' %>
<hr/>
<% end %>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")), groups_path, :class => 'btn'  %>
  
	<% if !current_user.nil? %>
	
		<% if @group.can_manage?(current_user) %>
			<%= link_to t('.edit', :default => t("helpers.links.edit")), edit_group_path(@group), :class => 'btn' %>
		<% end %>

	  <% if !current_user.is_member?(@group) %>  
	    <%= link_to 'Join', memberships_path(:group_id => @group), :class => 'btn ', id: 'join-btn', :method => :post, remote: true %>
	    <%= link_to 'Leave', membership_path(:group_id => @group), :class => 'btn btn-inverse', :id => 'leave-btn', :style => 'display:none;', :method => :delete, :confirm => "Are you sure you want to Leave #{@group.name}?", remote: true %> 
	  <% else %>           
	    <%= link_to 'Leave', membership_path(:group_id => @group), :class => 'btn btn-inverse', :id => 'leave-btn', :method => :delete, :confirm => "Are you sure you want to leave #{@group.name}?", remote: true %>
	    <%= link_to 'Join', memberships_path(:group_id => @group), :class => 'btn', :id => 'join-btn', :style => 'display:none;', :method => :post, remote: true %> 
	  <% end %>
			
			<% if current_user.is_member?(@group) %>
		  	<%= link_to t('.destroy', :default => t("helpers.links.destroy")), group_path(@group), :method => 'delete', :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger' %>
		<% end %>
		
	<% end %>
</div>