config/routes.rb
Cmunity::Application.routes.draw do

  # Devise Routes

  devise_for :users do
    get "login" => "devise/sessions#new", :as => :login
    delete "logout" => "devise/sessions#destroy", :as => :logout
    get "register" => "devise/registrations#new", :as => :register
  end
  # Root

  root :to => 'home#index'
  
  match "mycommunities" => "groups#index_my_groups"
  match "communities" => "groups#index"
  match "fetch" => "url_posts#fetch"
  match "fetchvid" => "video_posts#fetch"
  match "fetchimg" => "image_posts#fetch"

  #Autogenerated routes
  match "group_message" => "groups#send_message"
  
  #Autogenerated routes
  resources :activities
  resources :groups
  resources :users

  resources :contents, :path => "posts", :constraints => {:id => /[0-9]+/}, :as => "posts"
  resources :event_posts, :path => "posts/events", :as => "events"
  resources :video_posts, :path => "posts/videos", :as => "videos"
  resources :text_posts, :path => "posts/texts", :as => "texts"
  resources :url_posts, :path => "posts/urls", :as => "urls"
  resources :image_posts, :path => "posts/images", :as => "images"

  resources :memberships

end

app/views/shared/_account_dropdown.html.erb
<ul class="nav pull-right">
	<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><%= link_to "My Communities", mycommunities_path %></li>
      <li class="divider"></li>
      <li class="nav-header">Options</li>
      <li><%= link_to 'Change Password', edit_user_registration_path %></li>
      <li><%= link_to('Sign Out', destroy_user_session_path, :method => :delete)  %></li>
    </ul>
  </li>
</ul>

app/views/shared/_desktop_nav.haml
.well.sidebar-nav.span2
  %ul.nav.nav-list
    .desktop-post-nav
      %li.nav-header Post:
      %li= link_to '<i class="icon-pencil"></i> A Text'.html_safe, new_text_path
      %li= link_to '<i class="icon-calendar"></i> An Event'.html_safe, new_event_path
      %li= link_to '<i class="icon-camera"></i> An Image'.html_safe, new_image_path
      %li= link_to '<i class="icon-film"></i> A Video'.html_safe, new_video_path
      %li= link_to '<i class="icon-search"></i> A URL'.html_safe, new_url_path

app/views/shared/_error_messages.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-error
      This form contains #{pluralize(object.errors.count, "error")}.
      %ul
      - object.errors.full_messages.each do |msg|
        %li
          #{msg}

app/views/shared/_file_upload.haml
.well.text-center.photo_well.clearfix{:style => "display: inline-block; width: 270px;"} 
  %p.lead{:style => "margin: 0 0 5px;"} Upload an Image
  .fileupload.fileupload-new{"data-provides" => "fileupload"}
    .fileupload-new.thumbnail{:style => "width: #{width}px; height: #{height}px;"}
      %img{:src => "http://www.placehold.it/#{width}x#{height}/EFEFEF/AAAAAA&text=no+image"}/
    .fileupload-preview.fileupload-exists.thumbnail{:style => "max-width: #{width}px; max-height: #{height}px; line-height: 20px;"}
    %div
      %span.btn.btn-file{ :style => "margin: 0 0 5px 0;" }
        %span.fileupload-new Select image
        %span.fileupload-exists Change
        = f.file_field attribute.to_sym
      %a.btn.fileupload-exists{"data-dismiss" => "fileupload", :href => "#"} Remove

app/views/shared/_flash.haml
- if !flash.nil?
  - flash.each do |name, msg|
    - if msg.is_a?(String)
      %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
        %a.close{"data-dismiss" => "alert"} ×
        = content_tag :div, msg, :id => "flash_#{name}"

app/views/shared/_mobile_nav_long.haml
.mobile-post-nav-long
  %ul.auto-nav3.clearfix
    %li= link_to '<i class="icon-pencil"></i>'.html_safe, new_text_path, :class => "btn"
    %li= link_to '<i class="icon-calendar"></i>'.html_safe, new_text_path, :class => "btn"
    %li= link_to '<i class="icon-camera"></i>'.html_safe, new_text_path, :class => "btn"
    %li= link_to '<i class="icon-film"></i>'.html_safe, new_text_path, :class => "btn"
    %li= link_to '<i class="icon-search"></i>'.html_safe, new_text_path, :class => "btn"

app/views/shared/_mobile_nav_wide.haml
.mobile-post-nav-wide
  %ul.auto-nav2.clearfix
    %li= link_to '<i class="icon-pencil"></i>'.html_safe, new_text_path, :class => "btn btn-large"
    %li= link_to '<i class="icon-calendar"></i>'.html_safe, new_text_path, :class => "btn btn-large"
    %li= link_to '<i class="icon-camera"></i>'.html_safe, new_text_path, :class => "btn btn-large"
    %li= link_to '<i class="icon-film"></i>'.html_safe, new_text_path, :class => "btn btn-large"
    %li= link_to '<i class="icon-search"></i>'.html_safe, new_text_path, :class => "btn btn-large"

app/views/shared/_signin_dropdown.html.erb
<ul class="nav pull-right">
  <li><%= link_to "Register", register_path %></li>
	<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign In <b class="caret"></b></a>
    <ul class="dropdown-menu">
			<%= form_for("user", :url => user_session_path) do |f| %> 
		    <li><%= f.text_field :email , :size=>'15', :placeholder => 'Email' %><li>
		    <li><%= f.password_field :password , :size=>'15', :placeholder => "Password" %></li>
				<li><%= link_to t("user.submit"), "#", :class=>"btn btn-primary", :onclick=>"$('form').submit()" %> </li>
			<% end %>
      <li class="divider"></li>
      <li class="nav-header">More Options</li>
      <li><%= link_to "Forgot password?", new_password_path(:user) %></li>
    </ul>
  </li>
</ul>

app/views/shared/_tablet_nav.haml
.tablet-post-nav
  %ul.auto-nav1.clearfix
    %li= link_to '<i class="icon-pencil"></i> Text'.html_safe, new_text_path, :class => "btn"
    %li= link_to '<i class="icon-calendar"></i> Event'.html_safe, new_event_path, :class => "btn"
    %li= link_to '<i class="icon-camera"></i> Image'.html_safe, new_image_path, :class => "btn"
    %li= link_to '<i class="icon-film"></i> Video'.html_safe, new_video_path, :class => "btn"
    %li.last= link_to '<i class="icon-search"></i> URL'.html_safe, new_url_path, :class => "btn"