config/routes.rb
Cmunity::Application.routes.draw do

  # Devise Routes

  devise_for :users do
    get "login" => "devise/sessions#new", :as => :login
    delete "logout" => "devise/sessions#destroy", :as => :logout
    get "register" => "devise/registrations#new", :as => :register
  end
  # Root

  root :to => 'home#index'
  
  match "mycommunities" => "groups#index_my_groups"
  match "communities" => "groups#index"
  match "fetch" => "url_posts#fetch"
  match "fetchvid" => "video_posts#fetch"
  match "fetchimg" => "image_posts#fetch"

  #Autogenerated routes
  match "group_message" => "groups#send_message"
  
  #Autogenerated routes
  resources :activities
  resources :groups
  resources :users

  resources :contents, :path => "posts", :constraints => {:id => /[0-9]+/}, :as => "posts"
  resources :event_posts, :path => "posts/events", :as => "events"
  resources :video_posts, :path => "posts/videos", :as => "videos"
  resources :text_posts, :path => "posts/texts", :as => "texts"
  resources :url_posts, :path => "posts/urls", :as => "urls"
  resources :image_posts, :path => "posts/images", :as => "images"

  resources :memberships

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # Want to show all the posts of all types on the homepage for MVP
  def index
    @contents = Content.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contents }
    end
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_create_posts_buttons.html.erb
<center>
	<div class="btn-group">
		<button class="btn btn-primary"><%= link_to "New Text", new_text_path %></button>
		<button class="btn btn-primary"><%= link_to "New Event", new_event_path %></button>
		<button class="btn btn-primary"> <%= link_to "New URL", new_url_path %></button>
		<button class="btn btn-primary"><%= link_to "New Video", new_video_path %></button>
		<button class="btn btn-primary"><%= link_to "New Image", new_image_path %></button>
	</div>
</center>

app/views/home/_guest_home.html.erb
<%- model_class = Content -%>
<hr/>
<div class="row-fluid">
  <div class="span4">
    <center>
			<h2>Activity</h2>
    	<p>View posts, comments, pictures, and videos from users of CMUnity. </p>
    	<p><%= link_to "View Posts »", posts_path, :class=>"btn"%></p>
		</center>
  </div>
  <div class="span4">
		<center>
      <h2>Communities</h2>
      <p>Learn about and have the opportunity join various campus communities.</p>
      <p><%= link_to "View Communities »", communities_path, :class=>"btn"%></p>
		</center>
 </div>
  <div class="span4">
		<center>
      <h2>Events</h2>
      <p>Discover new activities and events to participate on and around campus.</p>
      <p><%= link_to "View Events »", posts_path, :class=>"btn"%></p>
		</center>
  </div>
</div>

app/views/home/_guest_pitch.html.erb
<div class="jumbotron">
	<center>
		<h1 id="jumbotron_h1">Meet CMUnity</h1>
		<p> 
			<font class="lead"> The mobile application that brings CMU's student organizations closer together</font>
			<br>
			<br>
			<i class="icon-star"></i>   promote and view new events and activities hosted around campus</li><br>
			<i class="icon-star"></i>   connect with student organizations and join them in their endeavors</li><br>
			<i class="icon-star"></i>   share cool new posts, pictures & videos to your campus community</li>
		</p>
		<br/>
		<%= render :partial => 'register_button' %>
		<br/>
	</center>
</div>
     

app/views/home/_register_button.html.erb
<div class="register">
	<center><%= link_to "Register", new_user_registration_path, :class=>'btn btn-large' %></center>
</div>
     

app/views/home/_user_home.html.erb
<%- model_class = Content -%>
<div class="row-fluid">
  <div class="span4">
    <center>
			<h2>Activity</h2>
    	<p>View posts and comments from users of CMUnity. You can share pictures and videos to friends and members of your organization about the latest news and events.</p>
    	<p><%= link_to "View Posts »", posts_path, :class=>"btn"%></p>
		</center>
  </div>
  <div class="span4">
		<center>
      <h2>Communities</h2>
      <p>Create or join communities and become a part of their endeavors and goals for the school year. Manage and organize your internal community's hierarchy and affairs. </p>
      <p><%= link_to "View Communities »", communities_path, :class=>"btn"%></p>
		</center>
 </div>
  <div class="span4">
		<center>
      <h2>Events</h2>
      <p>Create and promote events from your communities and share them with the rest of campus. What better way to publicize your events?</p>
      <p><%= link_to "View Events »", posts_path, :class=>"btn"%></p>
		</center>
  </div>
</div>

app/views/home/_user_pitch.html.erb
<hr/>
<div class="jumbotron">
	<center>
		<h1 id="jumbotron_h1">Welcome to CMUnity</h1>
		<p> 
			<font class="lead"> The mobile application that brings CMU's student organizations closer together</font>
			<br>
		</p>
	</center>
</div>
<hr/>

     

app/views/home/index.html.erb
<% if user_signed_in? %>
	<%= render :partial => 'create_posts_buttons' %>
	<%= render :partial => 'user_pitch' %>
	<%= render :partial => 'user_home' %>
<% else %>
	<%= render :partial => 'guest_pitch' %>
	<%= render :partial => 'guest_home' %>
<% end %>

<script type="text/javascript">
$(document).ready(function() {
    $.vegas('images/background.jpg')('overlay');
});
</script>